#* ************************************************************************** *#
#*                                                                            *#
#*                                                        :::      ::::::::   *#
#*   Makefile                                           :+:      :+:    :+:   *#
#*                                                    +:+ +:+         +:+     *#
#*   By: dwillems <dwillems@student.42.fr>          +#+  +:+       +#+        *#
#*                                                +#+#+#+#+#+   +#+           *#
#*   Created: 2015/12/25 19:56:50 by dwillems          #+#    #+#             *#
#*   Updated: 2015/12/25 19:57:23 by dwillems         ###   ########.fr       *#
#*                                                                            *#
#* ************************************************************************** *#

RESULT		=	gardening
SOURCES		=	gardening.ml
LIBS		=	graphics

include OCamlMakefile
