#* ************************************************************************** *#
#*                                                                            *#
#*                                                        :::      ::::::::   *#
#*   Makefile                                           :+:      :+:    :+:   *#
#*                                                    +:+ +:+         +:+     *#
#*   By: dwillems <dwillems@student.42.fr>          +#+  +:+       +#+        *#
#*                                                +#+#+#+#+#+   +#+           *#
#*   Created: 2015/12/24 12:51:51 by dwillems          #+#    #+#             *#
#*   Updated: 2015/12/24 12:56:50 by dwillems         ###   ########.fr       *#
#*                                                                            *#
#* ************************************************************************** *#

RESULT		=	ft_graphics
SOURCES		=	ft_graphics.ml
LIBS		=	graphics

include OCamlMakefile
